/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#72767c",
        "primary-container": "#00eefc",
        "on-error-container": "#ffa8a3",
        "on-error": "#490006",
        "secondary-fixed": "#ffc3bd",
        "surface-container-low": "#0f1419",
        "on-tertiary-fixed-variant": "#5b3b00",
        "primary-fixed-dim": "#00deec",
        "secondary-dim": "#e2242a",
        "secondary-fixed-dim": "#ffafa8",
        "on-tertiary-fixed": "#331f00",
        "error-dim": "#d7383b",
        "error": "#ff7168",
        "on-primary-container": "#005359",
        "secondary": "#ff7168",
        "surface-container-high": "#1b2027",
        "error-container": "#9f0519",
        "on-secondary-fixed": "#700009",
        "surface-tint": "#8ff5ff",
        "on-secondary-container": "#fff6f4",
        "surface-container": "#151a20",
        "inverse-primary": "#006a71",
        "on-background": "#f4f6fe",
        "surface": "#0a0e13",
        "on-primary-fixed-variant": "#005e64",
        "inverse-on-surface": "#51555b",
        "on-secondary": "#4a0004",
        "tertiary-fixed": "#faac1a",
        "surface-container-highest": "#21262e",
        "tertiary-fixed-dim": "#ea9f00",
        "surface-variant": "#21262e",
        "tertiary": "#ffbd58",
        "on-primary-fixed": "#003f43",
        "primary": "#8ff5ff",
        "background": "#0a0e13",
        "on-surface": "#f4f6fe",
        "surface-bright": "#262d35",
        "secondary-container": "#c00018",
        "on-tertiary-container": "#4f3300",
        "on-secondary-fixed-variant": "#a60013",
        "inverse-surface": "#f8f9ff",
        "outline-variant": "#44484e",
        "on-tertiary": "#5c3b00",
        "surface-dim": "#0a0e13",
        "primary-dim": "#00deec",
        "tertiary-dim": "#ea9f00",
        "tertiary-container": "#faac1a",
        "on-primary": "#005d63",
        "primary-fixed": "#00eefc",
        "on-surface-variant": "#a8abb2"
      },
      fontFamily: {
        "headline": ["Orbitron", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
